# load alpine image 
FROM alpine:latest 

#environement variables
ENV FLOW_COLLECTOR="localhost"
ENV COLLECTOR_PORT="2055"
ENV INTERFACE="eth0"

#install utils  
RUN apk update && apk add fprobe 


# removes fprobe configs 
#RUN rm -f /etc/default/fprobe
# replace fprobe config file
#COPY fprobe /etc/default/
ENTRYPOINT fprobe -i${INTERFACE} ${FLOW_COLLECTOR}:${COLLECTOR_PORT} && /bin/bash
