# load alpine image 
FROM alpine:latest 

RUN apk update && apk add fprobe && apk add bash


# removes fprobe configs 
#RUN rm -f /etc/default/fprobe
# replace fprobe config file
#COPY fprobe /etc/default/
ENTRYPOINT fprobe -i${INTERFACE} ${FLOW_COLLECTOR}:${COLLECTOR_PORT} && /bin/bash
